mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./h2db/estimate;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: admin
    password: psadmin
  sql:
    init:
      mode: ALWAYS
      schema-locations:
      - classpath:db/ddl/schema.sql
      data-locations:
      - classpath:db/dml/data.sql
      username: admin
      password: psadmin
      encoding: UTF-8
  h2:
    console:
      enabled: true